const express = require('express');
const router = express.Router();
const path = require('path');
const { createClient } = require('@supabase/supabase-js');
const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);
const PDFDocument = require('pdfkit');

// Enforce admin context globally across backend reports
const requireAdmin = (req, res, next) => {
    if (!req.session.admin) return res.redirect('/login');
    next();
};

// Compile advanced statistics dynamically generating rendering values
router.get('/dashboard', requireAdmin, async (req, res) => {
    try {
        const adminId = req.session.admin.id;
        
        const { data: quizzes } = await supabase.from('quizzes').select('*').eq('admin_id', adminId).order('created_at', { ascending: false });
        
        const totalQuizzes = quizzes ? quizzes.length : 0;
        const liveQuizzes = quizzes ? quizzes.filter(q => q.status === 'live').length : 0;
        const finishedQuizzes = quizzes ? quizzes.filter(q => q.status === 'ended').length : 0;
        
        let totalParticipants = 0;
        const mapCount = {};
        
        if (totalQuizzes > 0) {
            const quizIds = quizzes.map(q => q.id);
            const { count } = await supabase.from('participants').select('*', { count: 'exact', head: true }).in('quiz_id', quizIds);
            totalParticipants = count || 0;

            const { data: participantLogs } = await supabase.from('participants').select('quiz_id').in('quiz_id', quizIds);
            if (participantLogs) {
                participantLogs.forEach(p => { mapCount[p.quiz_id] = (mapCount[p.quiz_id] || 0) + 1; });
            }
        }
        
        if (quizzes) quizzes.forEach(q => q.participantCount = mapCount[q.id] || 0);

        res.render('dashboard', {
            admin: req.session.admin,
            quizzes: quizzes || [],
            stats: { totalQuizzes, liveQuizzes, finishedQuizzes, totalParticipants }
        });
    } catch (err) {
        console.error(err);
        res.status(500).send("Dashboard Loading Error");
    }
});

// Robust pure PDF streaming engine avoiding disk caching completely
router.get('/report/:quizCode', requireAdmin, async (req, res) => {
    try {
         const { data: quiz } = await supabase.from('quizzes').select('*').eq('code', req.params.quizCode).single();
         if (!quiz) return res.status(404).send('Quiz not found');

         const { data: participants } = await supabase.from('participants').select('*').eq('quiz_id', quiz.id).order('score', { ascending: false });
         
         const totalParts = participants ? participants.length : 0;
         let highestScore = 0;
         let avgScore = 0;
         let totalScore = 0;

         if (totalParts > 0) {
             highestScore = participants[0].score;
             totalScore = participants.reduce((acc, p) => acc + p.score, 0);
             avgScore = Math.round(totalScore / totalParts);
         }

         const doc = new PDFDocument({ margin: 50 });
         
         res.setHeader('Content-Type', 'application/pdf');
         res.setHeader('Content-Disposition', `attachment; filename=QuizReport-${quiz.code}.pdf`);
         
         doc.pipe(res);
         
         // Generate Header Block
         doc.fontSize(25).font('Helvetica-Bold').text('QuizArena PDF Report', { align: 'center' });
         doc.moveDown();
         
         doc.fontSize(14).font('Helvetica').text(`Quiz Title: ${quiz.title}`);
         doc.text(`Quiz Code: ${quiz.code}`);
         doc.text(`Date Generated: ${new Date().toLocaleDateString()}`);
         doc.moveDown();
         
         // Aggregate statistics
         doc.font('Helvetica-Bold').text(`Total Participants: ${totalParts}`);
         doc.text(`Highest Score: ${highestScore}`);
         doc.text(`Average Score: ${avgScore}`);
         doc.moveDown(2);

         doc.fontSize(18).text('Leaderboard');
         doc.moveDown();
         
         let rank = 1;
         doc.fontSize(12).font('Helvetica');
         if (totalParts === 0) {
             doc.text('No participants joined this quiz.');
         } else {
             // Structuring tables via positional coordinates
             doc.font('Helvetica-Bold');
             doc.text('Rank', 50, doc.y, { continued: true, width: 50 });
             doc.text('Player', 100, doc.y, { continued: true, width: 250 });
             doc.text('Score', 350, doc.y);
             doc.font('Helvetica');
             doc.moveDown(0.5);
             
             participants.forEach(p => {
                 doc.text(`${rank}`, 50, doc.y, { continued: true, width: 50 });
                 doc.text(`${p.name}`, 100, doc.y, { continued: true, width: 250 });
                 doc.text(`${p.score}`, 350, doc.y);
                 doc.moveDown(0.5);
                 rank++;
             });
         }
         
         doc.moveDown(4);
         doc.fontSize(10).fillColor('gray').text('Generated by QuizArena', { align: 'center' });
         
         doc.end();
    } catch (err) {
        console.error(err);
        res.status(500).send("Report Generation Error");
    }
});

module.exports = router;
